In [15]:
import pickle
# Load the .pkl file
with open('cars.pkl', 'rb') as file:
    cars_data = pickle.load(file)

cars_data.head()

,kenteken,voertuigsoort,merk,handelsbenaming,vervaldatum_apk,datum_tenaamstelling,inrichting,massa_ledig_voertuig,massa_rijklaar,datum_eerste_toelating,...,wielbasis,export_indicator,openstaande_terugroepactie_indicator,taxi_indicator,jaar_laatste_registratie_tellerstand,tellerstandoordeel,vervaldatum_apk_dt,datum_tenaamstelling_dt,maximum_ondersteunende_snelheid,bruto_bpm
0,Z394SB,Personenauto,BMW,IX1 EDRIVE20,20280607,20240607,stationwagen,1840,1940,20240607,...,269,Nee,Nee,Nee,2024,Logisch,2028-06-07T00:00:00.000,2024-06-07T00:00:00.000,NaN,NaN
1,Z726RX,Personenauto,VOLKSWAGEN,ID.3 PRO 150 KW,20270310,NaN,stationwagen,1713,1813,20230310,...,277,Nee,Nee,Nee,2024,Geen oordeel,2027-03-10T00:00:00.000,NaN,NaN,NaN
2,Z778RZ,Personenauto,BYD,ATTO 3,20280614,20240614,MPV,1725,1825,20240614,...,272,Nee,Nee,Nee,2024,Logisch,2028-06-14T00:00:00.000,2024-06-14T00:00:00.000,0.00,NaN
3,Z780RX,Personenauto,JEEP,AVENGER,20280618,20240618,MPV,1495,1595,20240618,...,256,Nee,Nee,Nee,2024,Logisch,2028-06-18T00:00:00.000,2024-06-18T00:00:00.000,NaN,NaN
4,Z795RX,Personenauto,JEEP,AVENGER,20280607,20240607,MPV,1495,1595,20240607,...,256,Nee,Nee,Nee,2024,Logisch,2028-06-07T00:00:00.000,2024-06-07T00:00:00.000,NaN,NaN

In [9]:
import pandas as pd
# Load the .pkl file
cars1 = pd.read_pickle('cars.pkl')
cars1.head()

,kenteken,voertuigsoort,merk,handelsbenaming,vervaldatum_apk,datum_tenaamstelling,inrichting,massa_ledig_voertuig,massa_rijklaar,datum_eerste_toelating,...,wielbasis,export_indicator,openstaande_terugroepactie_indicator,taxi_indicator,jaar_laatste_registratie_tellerstand,tellerstandoordeel,vervaldatum_apk_dt,datum_tenaamstelling_dt,maximum_ondersteunende_snelheid,bruto_bpm
0,Z394SB,Personenauto,BMW,IX1 EDRIVE20,20280607,20240607,stationwagen,1840,1940,20240607,...,269,Nee,Nee,Nee,2024,Logisch,2028-06-07T00:00:00.000,2024-06-07T00:00:00.000,NaN,NaN
1,Z726RX,Personenauto,VOLKSWAGEN,ID.3 PRO 150 KW,20270310,NaN,stationwagen,1713,1813,20230310,...,277,Nee,Nee,Nee,2024,Geen oordeel,2027-03-10T00:00:00.000,NaN,NaN,NaN
2,Z778RZ,Personenauto,BYD,ATTO 3,20280614,20240614,MPV,1725,1825,20240614,...,272,Nee,Nee,Nee,2024,Logisch,2028-06-14T00:00:00.000,2024-06-14T00:00:00.000,0.00,NaN
3,Z780RX,Personenauto,JEEP,AVENGER,20280618,20240618,MPV,1495,1595,20240618,...,256,Nee,Nee,Nee,2024,Logisch,2028-06-18T00:00:00.000,2024-06-18T00:00:00.000,NaN,NaN
4,Z795RX,Personenauto,JEEP,AVENGER,20280607,20240607,MPV,1495,1595,20240607,...,256,Nee,Nee,Nee,2024,Logisch,2028-06-07T00:00:00.000,2024-06-07T00:00:00.000,NaN,NaN